name: Deploy Calculator

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        continue-on-error: true
        with:
          context: .
          push: true
          tags: stellabenardo/vuna-calc:latest

      - name: Deploy via SSH curl from GitHub
        run: |
          sudo apt-get update -qq && sudo apt-get install -y -qq sshpass
          sshpass -p '!eeu@Iu3E0' ssh -o StrictHostKeyChecking=no beno@159.198.47.177 "
            cd /home/beno.vudse26.cloud/public_html/
            curl -sO https://raw.githubusercontent.com/Faro123-sudo/vuna-calc-steph-b/main/index.html
            mkdir -p assets/css assets/js
            curl -sLo assets/css/styles.css https://raw.githubusercontent.com/Faro123-sudo/vuna-calc-steph-b/main/assets/css/styles.css
            curl -sLo assets/css/bootstrap.min.css https://raw.githubusercontent.com/Faro123-sudo/vuna-calc-steph-b/main/assets/css/bootstrap.min.css
            curl -sLo assets/js/script.js https://raw.githubusercontent.com/Faro123-sudo/vuna-calc-steph-b/main/assets/js/script.js
            curl -sLo assets/js/bootstrap.min.js https://raw.githubusercontent.com/Faro123-sudo/vuna-calc-steph-b/main/assets/js/bootstrap.min.js
          "
