name: Deploy Calculator

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: stellabenardo
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: stellabenardo/vuna-calc:latest

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 159.198.47.177
          username: beno_deploy
          password: 'K#kzp4na!9Gnyvr1'
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.git/**
            **/.github/**
            **/Dockerfile
            **/.dockerignore
            **/LICENSE
            **/.vscode/**
